/**
 * Cities a branch can be in (Egypt). The key is stored in branches.city; names live in the apps.
 * Keep identical to apps/dashboard/src/lib/cities.ts and apps/mobile/src/lib/cities.ts.
 */
export const CITY_KEYS = [
  'cairo',
  'new_cairo',
  'helwan',
  'new_capital',
  'madinaty',
  'shorouk',
  'obour',
  'giza',
  'october_6',
  'sheikh_zayed',
  'alexandria',
  'borg_el_arab',
  'kafr_el_dawwar',
  'north_coast',
  'el_alamein',
  'marsa_matruh',
  'siwa',
  'shubra_el_kheima',
  'banha',
  'tanta',
  'mahalla',
  'mansoura',
  'zagazig',
  'tenth_of_ramadan',
  'damanhur',
  'kafr_el_sheikh',
  'desouk',
  'damietta',
  'shibin_el_kom',
  'port_said',
  'ismailia',
  'suez',
  'ain_sokhna',
  'faiyum',
  'beni_suef',
  'minya',
  'asyut',
  'sohag',
  'qena',
  'luxor',
  'aswan',
  'hurghada',
  'el_gouna',
  'safaga',
  'marsa_alam',
  'sharm_el_sheikh',
  'dahab',
  'el_tor',
  'arish',
  'kharga',
] as const;

export type CityKey = (typeof CITY_KEYS)[number];
